title: Syniah Peterson's Frontend Development Library Projects
#logo
description: Frontend Development Library Projects developed by Syniah Peterson
remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme
